# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\Luciano\Programas\cmake\bin\cmake.exe

# The command to remove a file.
RM = D:\Luciano\Programas\cmake\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Luciano\Programas-Src\Fast3D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Luciano\Programas-Src\Fast3D

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	D:\Luciano\Programas\CMake\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	D:\Luciano\Programas\CMake\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Luciano\Programas-Src\Fast3D\CMakeFiles D:\Luciano\Programas-Src\Fast3D\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Luciano\Programas-Src\Fast3D\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named unix

# Build rule for target.
unix: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 unix
.PHONY : unix

# fast build rule for target.
unix/fast:
	$(MAKE) -f CMakeFiles\unix.dir\build.make CMakeFiles/unix.dir/build
.PHONY : unix/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) -f CMakeFiles\core.dir\build.make CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named windows

# Build rule for target.
windows: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 windows
.PHONY : windows

# fast build rule for target.
windows/fast:
	$(MAKE) -f CMakeFiles\windows.dir\build.make CMakeFiles/windows.dir/build
.PHONY : windows/fast

#=============================================================================
# Target rules for targets named servers

# Build rule for target.
servers: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 servers
.PHONY : servers

# fast build rule for target.
servers/fast:
	$(MAKE) -f CMakeFiles\servers.dir\build.make CMakeFiles/servers.dir/build
.PHONY : servers/fast

#=============================================================================
# Target rules for targets named scene

# Build rule for target.
scene: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 scene
.PHONY : scene

# fast build rule for target.
scene/fast:
	$(MAKE) -f CMakeFiles\scene.dir\build.make CMakeFiles/scene.dir/build
.PHONY : scene/fast

#=============================================================================
# Target rules for targets named png

# Build rule for target.
png: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 png
.PHONY : png

# fast build rule for target.
png/fast:
	$(MAKE) -f CMakeFiles\png.dir\build.make CMakeFiles/png.dir/build
.PHONY : png/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f CMakeFiles\zlib.dir\build.make CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named gl_context

# Build rule for target.
gl_context: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 gl_context
.PHONY : gl_context

# fast build rule for target.
gl_context/fast:
	$(MAKE) -f CMakeFiles\gl_context.dir\build.make CMakeFiles/gl_context.dir/build
.PHONY : gl_context/fast

#=============================================================================
# Target rules for targets named nrex

# Build rule for target.
nrex: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 nrex
.PHONY : nrex

# fast build rule for target.
nrex/fast:
	$(MAKE) -f CMakeFiles\nrex.dir\build.make CMakeFiles/nrex.dir/build
.PHONY : nrex/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named driverstypes

# Build rule for target.
driverstypes: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 driverstypes
.PHONY : driverstypes

# fast build rule for target.
driverstypes/fast:
	$(MAKE) -f CMakeFiles\driverstypes.dir\build.make CMakeFiles/driverstypes.dir/build
.PHONY : driverstypes/fast

#=============================================================================
# Target rules for targets named editor

# Build rule for target.
editor: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 editor
.PHONY : editor

# fast build rule for target.
editor/fast:
	$(MAKE) -f CMakeFiles\editor.dir\build.make CMakeFiles/editor.dir/build
.PHONY : editor/fast

#=============================================================================
# Target rules for targets named FluxSol-GUI

# Build rule for target.
FluxSol-GUI: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 FluxSol-GUI
.PHONY : FluxSol-GUI

# fast build rule for target.
FluxSol-GUI/fast:
	$(MAKE) -f CMakeFiles\FluxSol-GUI.dir\build.make CMakeFiles/FluxSol-GUI.dir/build
.PHONY : FluxSol-GUI/fast

#=============================================================================
# Target rules for targets named core_

# Build rule for target.
core_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 core_
.PHONY : core_

# fast build rule for target.
core_/fast:
	$(MAKE) -f core\CMakeFiles\core_.dir\build.make core/CMakeFiles/core_.dir/build
.PHONY : core_/fast

#=============================================================================
# Target rules for targets named corebind_

# Build rule for target.
corebind_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 corebind_
.PHONY : corebind_

# fast build rule for target.
corebind_/fast:
	$(MAKE) -f core\bind\CMakeFiles\corebind_.dir\build.make core/bind/CMakeFiles/corebind_.dir/build
.PHONY : corebind_/fast

#=============================================================================
# Target rules for targets named coreio_

# Build rule for target.
coreio_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 coreio_
.PHONY : coreio_

# fast build rule for target.
coreio_/fast:
	$(MAKE) -f core\io\CMakeFiles\coreio_.dir\build.make core/io/CMakeFiles/coreio_.dir/build
.PHONY : coreio_/fast

#=============================================================================
# Target rules for targets named coremath_

# Build rule for target.
coremath_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 coremath_
.PHONY : coremath_

# fast build rule for target.
coremath_/fast:
	$(MAKE) -f core\math\CMakeFiles\coremath_.dir\build.make core/math/CMakeFiles/coremath_.dir/build
.PHONY : coremath_/fast

#=============================================================================
# Target rules for targets named coreos_

# Build rule for target.
coreos_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 coreos_
.PHONY : coreos_

# fast build rule for target.
coreos_/fast:
	$(MAKE) -f core\os\CMakeFiles\coreos_.dir\build.make core/os/CMakeFiles/coreos_.dir/build
.PHONY : coreos_/fast

#=============================================================================
# Target rules for targets named driverstypes_

# Build rule for target.
driverstypes_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 driverstypes_
.PHONY : driverstypes_

# fast build rule for target.
driverstypes_/fast:
	$(MAKE) -f drivers\CMakeFiles\driverstypes_.dir\build.make drivers/CMakeFiles/driverstypes_.dir/build
.PHONY : driverstypes_/fast

#=============================================================================
# Target rules for targets named zlib_

# Build rule for target.
zlib_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 zlib_
.PHONY : zlib_

# fast build rule for target.
zlib_/fast:
	$(MAKE) -f drivers\builtin_zlib\zlib\CMakeFiles\zlib_.dir\build.make drivers/builtin_zlib/zlib/CMakeFiles/zlib_.dir/build
.PHONY : zlib_/fast

#=============================================================================
# Target rules for targets named gl_context_

# Build rule for target.
gl_context_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 gl_context_
.PHONY : gl_context_

# fast build rule for target.
gl_context_/fast:
	$(MAKE) -f drivers\gl_context\CMakeFiles\gl_context_.dir\build.make drivers/gl_context/CMakeFiles/gl_context_.dir/build
.PHONY : gl_context_/fast

#=============================================================================
# Target rules for targets named gles2_

# Build rule for target.
gles2_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 gles2_
.PHONY : gles2_

# fast build rule for target.
gles2_/fast:
	$(MAKE) -f drivers\gles2\CMakeFiles\gles2_.dir\build.make drivers/gles2/CMakeFiles/gles2_.dir/build
.PHONY : gles2_/fast

#=============================================================================
# Target rules for targets named nrex_

# Build rule for target.
nrex_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 nrex_
.PHONY : nrex_

# fast build rule for target.
nrex_/fast:
	$(MAKE) -f drivers\nrex\CMakeFiles\nrex_.dir\build.make drivers/nrex/CMakeFiles/nrex_.dir/build
.PHONY : nrex_/fast

#=============================================================================
# Target rules for targets named png_

# Build rule for target.
png_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 png_
.PHONY : png_

# fast build rule for target.
png_/fast:
	$(MAKE) -f drivers\png\CMakeFiles\png_.dir\build.make drivers/png/CMakeFiles/png_.dir/build
.PHONY : png_/fast

#=============================================================================
# Target rules for targets named windows_

# Build rule for target.
windows_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 windows_
.PHONY : windows_

# fast build rule for target.
windows_/fast:
	$(MAKE) -f drivers\windows\CMakeFiles\windows_.dir\build.make drivers/windows/CMakeFiles/windows_.dir/build
.PHONY : windows_/fast

#=============================================================================
# Target rules for targets named unix_

# Build rule for target.
unix_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 unix_
.PHONY : unix_

# fast build rule for target.
unix_/fast:
	$(MAKE) -f drivers\unix\CMakeFiles\unix_.dir\build.make drivers/unix/CMakeFiles/unix_.dir/build
.PHONY : unix_/fast

#=============================================================================
# Target rules for targets named scene_

# Build rule for target.
scene_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 scene_
.PHONY : scene_

# fast build rule for target.
scene_/fast:
	$(MAKE) -f scene\CMakeFiles\scene_.dir\build.make scene/CMakeFiles/scene_.dir/build
.PHONY : scene_/fast

#=============================================================================
# Target rules for targets named scene2d_

# Build rule for target.
scene2d_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 scene2d_
.PHONY : scene2d_

# fast build rule for target.
scene2d_/fast:
	$(MAKE) -f scene\2d\CMakeFiles\scene2d_.dir\build.make scene/2d/CMakeFiles/scene2d_.dir/build
.PHONY : scene2d_/fast

#=============================================================================
# Target rules for targets named scene3d_

# Build rule for target.
scene3d_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 scene3d_
.PHONY : scene3d_

# fast build rule for target.
scene3d_/fast:
	$(MAKE) -f scene\3d\CMakeFiles\scene3d_.dir\build.make scene/3d/CMakeFiles/scene3d_.dir/build
.PHONY : scene3d_/fast

#=============================================================================
# Target rules for targets named scenegui_

# Build rule for target.
scenegui_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 scenegui_
.PHONY : scenegui_

# fast build rule for target.
scenegui_/fast:
	$(MAKE) -f scene\gui\CMakeFiles\scenegui_.dir\build.make scene/gui/CMakeFiles/scenegui_.dir/build
.PHONY : scenegui_/fast

#=============================================================================
# Target rules for targets named sceneio_

# Build rule for target.
sceneio_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sceneio_
.PHONY : sceneio_

# fast build rule for target.
sceneio_/fast:
	$(MAKE) -f scene\io\CMakeFiles\sceneio_.dir\build.make scene/io/CMakeFiles/sceneio_.dir/build
.PHONY : sceneio_/fast

#=============================================================================
# Target rules for targets named scenemain_

# Build rule for target.
scenemain_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 scenemain_
.PHONY : scenemain_

# fast build rule for target.
scenemain_/fast:
	$(MAKE) -f scene\main\CMakeFiles\scenemain_.dir\build.make scene/main/CMakeFiles/scenemain_.dir/build
.PHONY : scenemain_/fast

#=============================================================================
# Target rules for targets named main_

# Build rule for target.
main_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 main_
.PHONY : main_

# fast build rule for target.
main_/fast:
	$(MAKE) -f main\CMakeFiles\main_.dir\build.make main/CMakeFiles/main_.dir/build
.PHONY : main_/fast

#=============================================================================
# Target rules for targets named sceneresources_

# Build rule for target.
sceneresources_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sceneresources_
.PHONY : sceneresources_

# fast build rule for target.
sceneresources_/fast:
	$(MAKE) -f scene\resources\CMakeFiles\sceneresources_.dir\build.make scene/resources/CMakeFiles/sceneresources_.dir/build
.PHONY : sceneresources_/fast

#=============================================================================
# Target rules for targets named defaulttheme_

# Build rule for target.
defaulttheme_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 defaulttheme_
.PHONY : defaulttheme_

# fast build rule for target.
defaulttheme_/fast:
	$(MAKE) -f scene\resources\default_theme\CMakeFiles\defaulttheme_.dir\build.make scene/resources/default_theme/CMakeFiles/defaulttheme_.dir/build
.PHONY : defaulttheme_/fast

#=============================================================================
# Target rules for targets named app_

# Build rule for target.
app_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 app_
.PHONY : app_

# fast build rule for target.
app_/fast:
	$(MAKE) -f platform\windows\CMakeFiles\app_.dir\build.make platform/windows/CMakeFiles/app_.dir/build
.PHONY : app_/fast

#=============================================================================
# Target rules for targets named servers_

# Build rule for target.
servers_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 servers_
.PHONY : servers_

# fast build rule for target.
servers_/fast:
	$(MAKE) -f servers\CMakeFiles\servers_.dir\build.make servers/CMakeFiles/servers_.dir/build
.PHONY : servers_/fast

#=============================================================================
# Target rules for targets named visualserver_

# Build rule for target.
visualserver_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 visualserver_
.PHONY : visualserver_

# fast build rule for target.
visualserver_/fast:
	$(MAKE) -f servers\visual\CMakeFiles\visualserver_.dir\build.make servers/visual/CMakeFiles/visualserver_.dir/build
.PHONY : visualserver_/fast

#=============================================================================
# Target rules for targets named editor_

# Build rule for target.
editor_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 editor_
.PHONY : editor_

# fast build rule for target.
editor_/fast:
	$(MAKE) -f tools\editor\CMakeFiles\editor_.dir\build.make tools/editor/CMakeFiles/editor_.dir/build
.PHONY : editor_/fast

#=============================================================================
# Target rules for targets named editorioplugins_

# Build rule for target.
editorioplugins_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 editorioplugins_
.PHONY : editorioplugins_

# fast build rule for target.
editorioplugins_/fast:
	$(MAKE) -f tools\editor\io_plugins\CMakeFiles\editorioplugins_.dir\build.make tools/editor/io_plugins/CMakeFiles/editorioplugins_.dir/build
.PHONY : editorioplugins_/fast

#=============================================================================
# Target rules for targets named editorplugins_

# Build rule for target.
editorplugins_: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 editorplugins_
.PHONY : editorplugins_

# fast build rule for target.
editorplugins_/fast:
	$(MAKE) -f tools\editor\plugins\CMakeFiles\editorplugins_.dir\build.make tools/editor/plugins/CMakeFiles/editorplugins_.dir/build
.PHONY : editorplugins_/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... unix
	@echo ... core
	@echo ... windows
	@echo ... servers
	@echo ... scene
	@echo ... png
	@echo ... zlib
	@echo ... gl_context
	@echo ... nrex
	@echo ... main
	@echo ... driverstypes
	@echo ... editor
	@echo ... FluxSol-GUI
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... core_
	@echo ... corebind_
	@echo ... coreio_
	@echo ... coremath_
	@echo ... coreos_
	@echo ... driverstypes_
	@echo ... zlib_
	@echo ... gl_context_
	@echo ... gles2_
	@echo ... nrex_
	@echo ... png_
	@echo ... windows_
	@echo ... unix_
	@echo ... scene_
	@echo ... scene2d_
	@echo ... scene3d_
	@echo ... scenegui_
	@echo ... sceneio_
	@echo ... scenemain_
	@echo ... main_
	@echo ... sceneresources_
	@echo ... defaulttheme_
	@echo ... app_
	@echo ... servers_
	@echo ... visualserver_
	@echo ... editor_
	@echo ... editorioplugins_
	@echo ... editorplugins_
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

